//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XTool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfAsciiMap xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;AsciiMap&gt;
        ///		&lt;Int&gt;0&lt;/Int&gt;
        ///		&lt;Oct&gt;0&lt;/Oct&gt;
        ///		&lt;Hex&gt;0&lt;/Hex&gt;
        ///		&lt;Bin&gt;0&lt;/Bin&gt;
        ///		&lt;Symbol&gt;NUL&lt;/Symbol&gt;
        ///		&lt;Html&gt;&amp;amp;#000;&lt;/Html&gt;
        ///		&lt;Name /&gt;
        ///		&lt;Description&gt;Null char&lt;/Description&gt;
        ///		&lt;Printable&gt;false&lt;/Printable&gt;
        ///		&lt;IsAlpha&gt;false&lt;/IsAlpha&gt;
        ///		&lt;IsNumeric&gt;false&lt;/IsNumeric&gt;
        ///		&lt;IsExtendedChar&gt;false&lt;/IsExtendedChar&gt;
        ///		&lt;ResolvesToAlpha&gt;false&lt;/ResolvesToAlph [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AsciiMap {
            get {
                return ResourceManager.GetString("AsciiMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfCommandTemplate xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;CommandTemplate xsi:type=&quot;MySqlCommandTemplate&quot; id=&quot;e4befc1a-a1c7-474f-9c20-13c671b919b6&quot; name=&quot;MySql Tables-Columns&quot; groupName=&quot;groupName&quot; provider=&quot;MySql&quot; templateType=&quot;System&quot;&gt;
        ///    &lt;Description&gt;desc&lt;/Description&gt;
        ///    &lt;Command&gt; SELECT TABLE_SCHEMA AS Catalog, &apos;{catalog}&apos; as TableSchema, TABLE_NAME as TableName, COLUMN_NAME as ColumnName,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CommandTemplates {
            get {
                return ResourceManager.GetString("CommandTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string cyclops_facets_apirequest {
            get {
                return ResourceManager.GetString("cyclops_facets_apirequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.FacetGroup,a.FacetKey,a.FacetValue,a.FacetGroup,a.InstanceCount
        ///from
        ///(
        ///SELECT DISTINCT TOP (100) PERCENT Severity AS [FacetValue], &apos;Severity&apos; AS [FacetKey], &apos;Error&apos; AS [FacetGroup], count([&lt;schema&gt;].[Error].Id) as [InstanceCount]
        ///FROM [&lt;schema&gt;].[Error] (nolock)
        ///WHERE [CreatedAt] &gt;= @From AND [CreatedAt] &lt;= @To
        ///GROUP BY [Severity]
        ///
        ///UNION SELECT DISTINCT TOP (100) PERCENT [Zone] AS [FacetValue], &apos;Zone&apos; AS [FacetKey], &apos;Error&apos; AS [FacetGroup], count([&lt;schema&gt;].[Error].Id) as [InstanceCount]
        ///F [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cyclops_facets_error {
            get {
                return ResourceManager.GetString("cyclops_facets_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   SELECT a.FacetGroup, a.FacetKey, a.FacetVAlue,a.FacetGroup,a.InstanceCount
        ///  FROM
        ///  (
        ///	SELECT DISTINCT TOP (100) PERCENT CONVERT(nvarchar(36),[BasicToken]) as [FacetValue], &apos;BasicToken&apos; AS [FacetKey],&apos;Session&apos; AS [FacetGroup], count([&lt;schema&gt;].[Session].[Id]) as [InstanceCount]
        ///	FROM [&lt;schema&gt;].[Session] (nolock)
        ///	WHERE [CreatedAt] &gt;= @From AND [CreatedAt] &lt;= @To
        ///	GROUP BY CONVERT(nvarchar(36),[BasicToken])
        ///
        ///	UNION SELECT DISTINCT TOP (100) PERCENT CONVERT(nvarchar(12),[TenantId]) as [FacetValue], [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cyclops_facets_session {
            get {
                return ResourceManager.GetString("cyclops_facets_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id],[XmlData]
        ///  FROM [&lt;schema&gt;].[Error]
        ///  where [Id] = @id.
        /// </summary>
        public static string cyclops_get_error_xml {
            get {
                return ResourceManager.GetString("cyclops_get_error_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// e.[Id]
        ///      ,e.[CreatedAt]
        ///	  ,DATENAME(month,e.[CreatedAt]) as [Month]
        ///	  ,DATENAME(day,e.[CreatedAt]) as [Day]
        ///      ,e.[ApplicationKey]
        ///      ,e.[Zone]
        ///      ,e.[AppContextInstance]
        ///      ,e.[MessageId]
        ///      ,e.[Category]
        ///      ,e.[Severity]
        ///      ,e.[Message]
        ///	  ,r.[ApiRequestId]
        ///	  ,s.[Id] as [SessionId]
        ///      --,[XmlData]
        ///FROM [&lt;schema&gt;].ApiRequest r LEFT OUTER JOIN
        ///                         [&lt;schema-session&gt;].Session s ON r.BearerToken = s.BearerToken RIGHT OUTER JOIN
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cyclops_search_error {
            get {
                return ResourceManager.GetString("cyclops_search_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string cyclops_search_session {
            get {
                return ResourceManager.GetString("cyclops_search_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlServer,Clr,Db,SqlDb,DbTypeAssessor,SqlTypeAssessor
        ///bigint,Int64,Int64,BigInt,GetInt64,GetSqlInt64
        ///binary,Byte[],Binary,VarBinary,GetBytes,GetSqlBinary
        ///bit,Boolean,Boolean,Bit,GetBoolean,GetSqlBoolean
        ///char,String,&quot;AnsiStringFixedLength,&quot;,Char,GetString,GetSqlString
        ///date,DateTime,Date,Date,GetDateTime,GetSqlDateTime
        ///datetime,DateTime,DateTime,DateTime,GetDateTime,GetSqlDateTime
        ///datetime2,DateTime,DateTime2,DateTime2,GetDateTime,None
        ///datetimeoffset,DateTimeOffset,DateTimeOffset,DateTimeOffset,GetDat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DataMaps {
            get {
                return ResourceManager.GetString("DataMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE [dbo].[DataMaps](
        ///	[fld_bigint] [bigint] NULL,
        ///	[fld_binary] [binary](50) NULL,
        ///	[fld_bit] [bit] NULL,
        ///	[fld_char] [char](10) NULL,
        ///	[fld_date] [date] NULL,
        ///	[fld_datetime] [datetime] NULL,
        ///	[fld_datetime2] [datetime2](7) NULL,
        ///	[fld_datetimeoffset] [datetimeoffset](7) NULL,
        ///	[fld_decimal] [decimal](18, 0) NULL,
        ///	[fld_float] [float] NULL,
        ///	[fld_geography] [geography] NULL,
        ///	[fld_geometry] [geometry] NULL,
        ///	[fld_hierarchyid] [hierarchyid] NULL,
        ///	[fld_image] [image] NULL,
        ///	[fld_i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DataMapsTable {
            get {
                return ResourceManager.GetString("DataMapsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SPECIFIC_SCHEMA AS [StoredProcedureSchema],
        ///		SPECIFIC_NAME AS [StoredProcedureName], 
        ///		ORDINAL_POSITION AS [OrdinalPosition], 
        ///		PARAMETER_MODE AS [Mode], 
        ///		PARAMETER_NAME AS [ParameterName], 
        ///		DATA_TYPE AS [Datatype],
        ///		CHARACTER_MAXIMUM_LENGTH AS [MaxLength]
        ///		 FROM INFORMATION_SCHEMA.[PARAMETERS] JOIN SYSOBJECTS so ON SPECIFIC_NAME = so.name
        ///		 WHERE so.xtype = &apos;P&apos; AND left(SPECIFIC_NAME,3) != &apos;sp_&apos;
        ///		 
        ///
        ///UNION ALL SELECT SPECIFIC_SCHEMA AS StoredProcedureSchema, 
        ///		name AS StoredPr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Discovery_StoredProcedures {
            get {
                return ResourceManager.GetString("Discovery_StoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @TableName varchar(150)
        ///DECLARE @Id int
        ///
        ///DECLARE cur CURSOR LOCAL FOR
        ///
        ///SELECT name,id
        ///FROM sysobjects
        ///WHERE type = &apos;u&apos; 
        ///AND left(name,2) &lt;&gt; &apos;DD&apos; 
        ///AND left(name,2) &lt;&gt; &apos;dt&apos;
        ///ORDER BY name
        ///
        ///OPEN cur
        ///	FETCH NEXT FROM cur INTO @TableName, @Id
        ///	WHILE @@FETCH_STATUS = 0
        ///	BEGIN
        ///	
        ///
        ///		SELECT	TABLE_CATALOG AS [Catalog], TABLE_SCHEMA AS [TableSchema], TABLE_NAME AS [TableName],  COLUMN_NAME AS [ColumnName],
        ///			ORDINAL_POSITION AS OrdinalPosition, COLUMN_DEFAULT AS DefaultValue,Convert(bit,(CAS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Discovery_Tables {
            get {
                return ResourceManager.GetString("Discovery_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_SCHEMA AS Catalog, &apos;[catalog]&apos; as TableSchema, TABLE_NAME as TableName, COLUMN_NAME as ColumnName,
        ///ORDINAL_POSITION AS OrdinalPosition, COLUMN_DEFAULT as DefaultValue,
        ///CASE WHEN IS_NULLABLE = &apos;YES&apos; THEN 1 ELSE 0 END AS IsNullible, DATA_TYPE AS Datatype,
        ///CHARACTER_MAXIMUM_LENGTH AS MaxLength, NULL AS IsComputed, 
        ///NULL AS ColumnLength, NULL AS IsIdentity, NULL AS IsRowGuidColumn,
        ///CASE WHEN COLUMN_KEY = &apos;PRI&apos; THEN 1 ELSE 0 END AS IsPrimaryKey,
        ///CASE WHEN COLUMN_KEY = &apos;MUL&apos; THEN 1 ELSE 0 END A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Discovery_Tables_MySql {
            get {
                return ResourceManager.GetString("Discovery_Tables_MySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
        ///FROM INFORMATION_SCHEMA.VIEWS.
        /// </summary>
        public static string Discovery_Views {
            get {
                return ResourceManager.GetString("Discovery_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;machine&quot;: &quot;HNLAP001659&quot;,
        ///  &quot;config&quot;: &quot;api&quot;,
        ///  &quot;mode&quot;: &quot;DEBUG&quot;,
        ///  &quot;registration&quot;: [
        ///    {
        ///      &quot;order&quot;: 1,
        ///      &quot;name&quot;: &quot;Bookmark&quot;,
        ///      &quot;methods&quot;: [
        ///        &quot;Post&quot;,
        ///        &quot;Delete&quot;
        ///      ],
        ///      &quot;endpoints&quot;: [
        ///        {
        ///          &quot;order&quot;: 1,
        ///          &quot;httpMethod&quot;: &quot;POST&quot;,
        ///          &quot;pattern&quot;: &quot;v{version}/media/{mediaId}/bookmarks/{token}?f={f}&amp;p={p}&quot;,
        ///          &quot;controller&quot;: &quot;Bookmark&quot;,
        ///          &quot;controllerMethod&quot;: &quot;Post&quot;,
        ///          &quot;parameters&quot;: [
        ///            {
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
    }
}
